name: Repackage MCP

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Check Python Version
        run: |
          alias python=python2
          python --version
      - name: Run Setup
        shell: bash
        run: |
          alias python=python2
          sudo apt install dos2unix zip
          ./setupFML1.2.5.sh
      - name: Zip the Repository
        run: zip -r release.zip .
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.0
          release_name: Release v0.0.0
          draft: false
          prerelease: false
      - name: Upload Release
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
